const appointmentsEnums = {
  GET_APPOINTMENT: "GET_APPOINTMENT",
  GET_APPOINTMENT_SUCCESS: "GET_APPOINTMENT_SUCCESS",
  GET_APPOINTMENT_ERROR: "GET_APPOINTMENT_ERROR",

  CREATE_APPOINTMENT: "CREATE_APPOINTMENT",
  CREATE_APPOINTMENT_SUCCESS: "CREATE_APPOINTMENT_SUCCESS",
  CREATE_APPOINTMENT_ERROR: "CREATE_APPOINTMENT_ERROR",  

  UPDATE_APPOINTMENT: "UPDATE_APPOINTMENT",
  UPDATE_APPOINTMENT_SUCCESS: "UPDATE_APPOINTMENT",
  UPDATE_APPOINTMENT_ERROR: "UPDATE_APPOINTMENT",

  DELETE_APPPOINTMENT: "DELETE_APPPOINTMENT",
  DELETE_APPPOINTMENT_SUCCESS: "DELETE_APPPOINTMENT_SUCCESS",
  DELETE_APPPOINTMENT_ERROR: "DELETE_APPPOINTMENT_ERROR",
};

export default appointmentsEnums;
