const appointmentsEnums = {
  GET_APPOINTMENT: "GET_APPOINTMENT",
  GET_APPOINTMENT_SUCCESS: "GET_APPOINTMENT_SUCCESS",
  GET_APPOINTMENT_ERROR: "GET_APPOINTMENT_ERROR",

  SEND_APPOINTMENT: "SEND_APPOINTMENT",
  SEND_APPOINTMENT_SUCCESS: "SEND_APPOINTMENT_SUCCESS",
  SEND_APPOINTMENT_ERROR: "SEND_APPOINTMENT_ERROR",
  
  UPDATE_APPOINTMENT: "UPDATE_APPOINTMENT",
  UPDATE_APPOINTMENT_SUCCESS: "UPDATE_APPOINTMENT",
  UPDATE_APPOINTMENT_ERROR: "UPDATE_APPOINTMENT",
};

export default appointmentsEnums;
