const taskEnums = {
  ADD_USER: "ADD_USER",
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  ADD_USER_ERROR: "ADD_USER_ERROR",

  LOGIN_USER: "LOGIN_USER",
  LOGIN_USER_SUCCESS: "LOGIN_USER_SUCCESS",
  LOGIN_USER_ERROR: "LOGIN_USER_ERROR",

  SEND_APPOINTMENT: "SEND_APPOINTMENT",
  SEND_APPOINTMENT_SUCCESS: "SEND_APPOINTMENT_SUCCESS",
  SEND_APPOINTMENT_ERROR: "SEND_APPOINTMENT_ERROR",

  RENAME_APPOINTMENT: "RENAME_APPOINTMENT",
  RENAME_APPOINTMENT_SUCCESS: "RENAME_APPOINTMENT_SUCCESS",
  RENAME_APPOINTMENT_ERROR: "RENAME_APPOINTMENT_ERROR",

  DELETE_APPOINTMENT: "DELETE_APPOINTMENT",
  DELETE_APPOINTMENT_SUCCESS: "DELETE_APPOINTMENT_SUCCESS",
  DELETE_APPOINTMENT_ERROR: "DELETE_APPOINTMENT_ERROR",
};

export default taskEnums;
